<?php

/** @var $block \Doofinder\Feed\Block\Adminhtml\Setup */

?>
<?php $sector = $block->getSectorValue() ?>
<div data-role="steps-setup-main" class="steps-setup">
    <div class="steps-col-container">
        <div class="steps-col">
            <img alt="<?= $escaper->escapeHtmlAttr(__('Doofinder Feed Setup')) ?>"
                 src="<?= /* @noEscape */ $block->getViewFileUrl('Doofinder_Feed::images/doofinder-logo.png') ?>" />
            <div class="steps-buttons-col">
                <div class="steps-button-title">
                    <h2><?= $escaper->escapeHtmlAttr(__('Step 1:')) ?></h2>
                    <h4><?= $escaper->escapeHtmlAttr(__('We select the sector of our platform')) ?></h4>
                    <div class="steps-button-container">
                        <select id="sector-selector">
                            <option value="" disabled<?php if (!$sector): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Choose the sector of your ecommerce')) ?>
                            </option>
                            <option value="fashion" <?php if ($sector === "fashion"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Apparel & Accessories')) ?>
                            </option>
                            <option value="autos" <?php if ($sector === "autos"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Auto Parts & Accessories')) ?>
                            </option>
                            <option value="childcare" <?php if ($sector === "childcare"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Childcare')) ?>
                            </option>
                            <option value="food" <?php if ($sector === "food"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Food & Beverages')) ?>
                            </option>
                            <option value="home" <?php if ($sector === "home"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Home & Garden')) ?>
                            </option>
                            <option value="leisure" <?php if ($sector === "leisure"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Leisure & Culture')) ?>
                            </option>
                            <option value="others" <?php if ($sector === "others"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Others')) ?>
                            </option>
                            <option value="pets" <?php if ($sector === "pets"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Pets')) ?>
                            </option>
                            <option 
                                value="parapharmacy" <?php if ($sector === "parapharmacy"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Pharma & Cosmetics')) ?>
                            </option>
                            <option value="sport" <?php if ($sector === "sport"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Sport & Fitness')) ?>
                            </option>
                            <option value="technology" <?php if ($sector === "technology"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Tech Products & Electronics')) ?>
                            </option>
                            <option value="toys" <?php if ($sector === "toys"): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtmlAttr(__('Toys & Hobbies')) ?>
                            </option>
                        </select>
                    </div>
                </div>
                <div class="steps-button-title">
                    <h2><?= $escaper->escapeHtmlAttr(__('Step 2:')) ?></h2>
                    <h4><?= $escaper->escapeHtmlAttr(__('We link to our Doofinder account')) ?></h4>
                    <div class="steps-button-container">
                        <input
                            class="steps-btn-yellow" 
                            id="register-account-btn" 
                            disabled 
                            type="button" 
                            value="<?= $escaper->escapeHtmlAttr(__('USE YOUR FREE TRIAL NOW!')) ?>" 
                        />
                    </div>
                    <div class="steps-button-container">
                        <input
                            disabled 
                            type="button" 
                            id="login-btn" 
                            value="<?= $escaper->escapeHtmlAttr(__('I HAVE AN ACCOUNT')) ?>" 
                        />
                    </div>
                </div>
            </div>
        </div>

        <div class="steps-col">
            <div class="steps-description">
                <h2 class="steps-head">
                    <?= $escaper->escapeHtmlAttr(
                        __('Add a smart search engine to your e-commerce in 5 minutes and with no programming')
                    ); ?>
                </h2>
                <h3 id="steps-about"><?= $escaper->escapeHtmlAttr(__('ABOUT DOOFINDER:')) ?></h3>
                <p><?= $escaper->escapeHtmlAttr(
                    __('Doofinder provides you with an instant search layer to display 
                    your products when your visitors use the Doofinder script.')
                ); ?></p>
                <p><?= $escaper->escapeHtmlAttr(
                    __('Your customers then have the opportunity to preview your products, 
                    filter them and choose the desired product. 
                    Upon hitting enter, doofinder will power also the results page.')
                ); ?></p>
                <p><?= $escaper->escapeHtmlAttr(__('Among our features are:')) ?></p>
                <ul>
                    <li>
                        <?= $escaper->escapeHtmlAttr(__('Detailed reports on search behaviour.')) ?>
                    </li>
                    <li>
                        <?= $escaper->escapeHtmlAttr(__('Faceted search option.')) ?>
                    </li>
                    <li>
                        <?= $escaper->escapeHtmlAttr(__('Learning behaviour')) ?>
                    </li>
                    <li>
                        <?= $escaper->escapeHtmlAttr(__('Merchandising power to set a products positioning.')) ?>
                    </li>
                    <li>
                        <?= $escaper->escapeHtmlAttr(
                            __('Banner feature for advertising and promoting products, brands and events.')
                        ); ?>
                    </li>
                    <li>
                        <?= $escaper->escapeHtmlAttr(__('Options to redirect users to content pages.')) ?>
                    </li>
                    <li>
                        <?= $escaper->escapeHtmlAttr(__('Held on our servers for a faster page load time.')) ?>
                    </li>
                </ul>
                <p><?= $escaper->escapeHtmlAttr(
                    __('More than 5000 e-commerces sites over 35 countries are already using it.')
                ); ?></p>
            </div>
        </div>

        <div class="ajax-steps-col">
            <img alt="<?= $escaper->escapeHtmlAttr(__('Doofinder Feed Setup')) ?>"
                 src="<?= /* @noEscape */ $block->getViewFileUrl('Doofinder_Feed::images/doofinder.png') ?>" />
            <h3 id="message-ajax-steps"></h3>
            <div class="setup-finish-buttons hidden">
                <a href="<?= $escaper->escapeUrl($block->getIndexProcessingStatusUrl()) ?>" class="doofinder-button">
                    <?= $escaper->escapeHtml(__('Check index processing status')) ?>
                </a>
                <a href="<?= $escaper->escapeUrl($block->getDoofinderConfigurationUrl()) ?>" class="doofinder-button">
                    <?= $escaper->escapeHtml(__('Go to configuration')) ?>
                </a>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Doofinder_Feed/js/initial": {
                "component": "Doofinder_Feed/js/initial",
                "submit_url": "<?= $escaper->escapeUrl($block->getSaveUrl()) ?>",
                "save_config_url": "<?= $escaper->escapeUrl($block->getSaveConfigUrl()) ?>",
                "permissionsDialogUrl": "<?= $escaper->escapeUrl($block->getPermissionsDialogUrl()) ?>",
                "tokensDialogUrl": "<?= $escaper->escapeUrl($block->getTokensDialogUrl()) ?>",
                "accessTokenUrl": "<?= $escaper->escapeUrl($block->getAccessTokenUrl()) ?>",
                "saveSectorUrl": "<?= $escaper->escapeUrl($block->getSaveSectorUrl()) ?>",
                "currentSectorValue": "<?= $escaper->escapeHtml($block->getSectorValue()) ?>",
                "sectorSelector": "#sector-selector",
                "buttonRegister": "#register-account-btn",
                "buttonLogin": "#login-btn",
                "email": "<?= $escaper->escapeHtml(
                    $block->helper(Doofinder\Feed\Helper\StoreConfig::class)->getEmailAdmin()
                ); ?>",
                "name": "<?= $escaper->escapeHtml(
                    $block->helper(Doofinder\Feed\Helper\StoreConfig::class)->getIntegrationName()
                ); ?>",
                "isIntegrationCreated": "<?= $escaper->escapeHtml($block->isIntegrationCreated()) ?>",
                "hasApiKey": "<?= $escaper->escapeHtml($block->hasApiKey()) ?>",
                "installingLoopStatus": "<?= $escaper->escapeHtml($block->getInstallingLoopStatus()) ?>"
            },
            "Doofinder_Feed/js/link-account": {
                "component": "Doofinder_Feed/js/link-account",
                "buttonRegister": "#register-account-btn",
                "buttonLogin": "#login-btn",
                "signupEndpoint": "<?= $escaper->escapeUrl(
                    $block->helper(Doofinder\Feed\Helper\StoreConfig::class)->getSignupEndpoint()
                ); ?>",
                "loginEndpoint": "<?= $escaper->escapeUrl(
                    $block->helper(Doofinder\Feed\Helper\StoreConfig::class)->getLoginEndpoint()
                ); ?>",
                "paramsPopup": "<?= $escaper->escapeHtml($block->getParamsPopup()) ?>",
                "checkAPIKeyUrl": "<?= $escaper->escapeUrl($block->getCheckAPIKeyUrl()) ?>",
                "setupUrl": "<?= $escaper->escapeUrl($block->getSetupUrl()) ?>",
                "doofinderConnectUrl": "<?= $escaper->escapeUrl($block->getDoofinderConnectUrl()) ?>"
            }
        }
    }
</script>
