<?php
/**
 * @var \Doofinder\Feed\Block\Banner $block
 */

$banner = $block->getBanner();
?>
<?php if ($banner): ?>
    <div class="search-result-banner">
        <a href="<?= $block->escapeHtml($banner['link']); ?>"
            <?= $banner['blank'] ? 'target="_blank"' : ''; ?>
            data-banner-id="<?= $block->escapeHtml($banner['id']); ?>">
                <img src="<?= $block->escapeHtml($banner['image']); ?>" alt="Doofinder Banner"/>
        </a>
    </div>
    <script type="text/x-magento-init">
        {
            ".search-result-banner": {
                "banner": {
                    "ajaxUrl": "<?= $block->escapeJs($block->getAjaxUrl()); ?>",
                    "bannerInsertionPoint": "<?= $block->escapeJs($banner['insertion_point']); ?>",
                    "bannerInsertionMethod": "<?= $block->escapeJs($banner['insertion_method']); ?>"
                }
            }
        }
    </script>
<?php endif ?>
