dist: xenial
root: true
language: php

services:
  - mysql
  - elasticsearch

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
  - php: 7.0
    env: MAGENTO_VERSION=2.2.6
  - php: 7.1
    env: MAGENTO_VERSION=2.2.11
  - php: 7.1
    env: MAGENTO_VERSION=2.3.1
  - php: 7.2
    env: MAGENTO_VERSION=2.3.3
  - php: 7.3
    env: MAGENTO_VERSION=2.3.5-p1
  - php: 7.4
    env: MAGENTO_VERSION=2.4.1

env:
  global:
    - MYSQL_HOST=127.0.0.1
    - MYSQL_USER=magento
    - MYSQL_PASSWORD=magento
    - MAGENTO_PATH=../magento
    - MODULE_NAME=doofinder/doofinder-magento2
    - MAGENTO_ADMIN_FIRSTNAME=Admin
    - MAGENTO_ADMIN_LASTNAME=MyStore
    - MAGENTO_ADMIN_EMAIL=amdin@example.com
    - MAGENTO_ADMIN_USERNAME=admin
    - MAGENTO_ADMIN_PASSWORD=admin123
    - MAGENTO_TEST_CLEANUP=0
    - secure: YONkNzW+1zZgzScoqIFYO7AbfvBac2hAH5nvkCiBwVbCiq4UIT8dXdJQDM/VYylMROKlFYNyEUBQKOLteWc8iiUiAwa6oh2BZbE491t4dn6o85qfqqBch6+BCcbnUFqFD7gTc2qWLeeCyYUnxgv3STYIzx3sob2qkUy4w1rRebJeUKz66WgRQE/nvTdAVZ44Ttl0V5zxPqO2YxOA69I4qFaRSQgOSenSquoc7ekJCFGZz1/yGLeHlpRlL9VGoXL8qJUDtS4cQ/TA/DpCKCaAFXGTfqg/hx+3b/8ZQeYKxCf/7rNt1xjGG+92dJLe+kwgScGgdGP3vN7+n24Mzmt5VkGM1/fE7c3or5gKvD8K7tkfE3YwGDAGA+MrsM4L5Nq3m9MgwRAbK1IdYr1gppnCbHWnVb4L8yTC0zBl7gjQgCBzD/OD+soSGyCTKQjjLvEq1+HC8EBKWiu+6krzxPsoSTtp5x209SNNODOkGgxBYwvqIT2iOUxwtzlE2R7ZnvCUO+5CMV5ZqpF0e5Ybcca5jUoFmwgNxeM3mQ02lWcp3f9lZ+j2lStjB21x1rlnFC38JsCytrLTbkGFLA/jipeVUaEZA1XKLFgv/vW99hnQVjtP1xCmW36MeTfsih8ASyhRNZbfMcbXZi08a7ZM3ZiEujmqUlJNqqgjvgMJIemUodA=
    - secure: DfmHJm+tis7WTjtvJKnxxPlXrd7jbRNgRKzhOScaW2Jo3vHSm09WZKiLFyR9ZoHoAnKbft2cyKGRw2pPlfZBe9/GwUVhTp6ndFKuNDVFyoRoVMJb+B9TS/LLCqtOy+NsUV2l6lDfeU8XNuKY6cVpznaL3Vugc5AhWsG96M+eZesaOjvr9zp35Y92iHhiYHvh16WlBhw+6Jjz2sGFawIP1cjC3tge6KYQrpvI5Jd+1q943NtnAr+t2IobI0KuNPie2K49T1W5WBijSL7xqAnQoUsc/Svu2WahrLjxQnE5HUQ0G2xut884ZYwRNROMItLtSDl7Sr18ZREyuK8WBGwuNoAxkNCSRh++4m4rNAjl0KeuyI/wJlyNPzAbCBYHH+IxdC06qriK8BPejeoB4nRbZd7aUX1QjD6Lrskm4n2o30yOK98WkvEYUkmNTG0qUkFSA2gHCPbOAiRbt2rS3eFtDGsrZy4Fr6o/RdYnu9D2x3Jutc9USPMCrPTzJBhjfn3fc8yvfFxKfqSxSzB4jhgC06iSTXzlo4xv4fOYg2xrsHr8JFc3GLt+WiwtEq9g9FlUTXJN4U6KmVabCqSlYSfAfK6w4iqUQYIjUbYR8m51u/kyGJb3rFwWyXJIgtKMgfink8i3MW8u5u2f4X8hAvFEjSB2JKpAV+p3Sm23HNkYBgo=

before_install:
  - composer self-update --1 || composer --version
  - mysql -e 'CREATE DATABASE magento_integration_tests;'
  - mysql -e "GRANT ALL PRIVILEGES ON magento_integration_tests.* TO 'magento'@'localhost' IDENTIFIED BY 'magento';"
  - mysql -e 'FLUSH PRIVILEGES;'
  - composer config --global http-basic.repo.magento.com "$MAGENTO_AUTH_USER" "$MAGENTO_AUTH_PASSWORD"
  # Remove Xdebug.
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis.php.ini

install:
  - composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition "$MAGENTO_PATH" "$MAGENTO_VERSION"
  - |-
    composer config -d "$MAGENTO_PATH" repositories.0 "{\"type\": \"path\", \"url\": \"$TRAVIS_BUILD_DIR\"}" 2>/dev/null
    composer config -d "$MAGENTO_PATH" repositories.1 "{\"type\": \"composer\", \"url\": \"https://repo.magento.com/\"}" 2>/dev/null
  - composer require -d "$MAGENTO_PATH" "$MODULE_NAME @dev"
  - cp Test/ci/install-config-mysql.php "$MAGENTO_PATH/dev/tests/integration/etc/install-config-mysql.php"

script:
  - bash -c 'cd "$MAGENTO_PATH/dev/tests/unit" && php ../../../vendor/bin/phpunit ../../../vendor/doofinder/doofinder-magento2/Test/Unit'
  - bash -c 'cd "$MAGENTO_PATH/dev/tests/integration" && php ../../../vendor/bin/phpunit ../../../vendor/doofinder/doofinder-magento2/Test/Integration'

before_deploy:
  - git archive --format=zip -o doofinder-magento2.zip $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: x5Q57V+JuldWyHxsETjxggCLFMAl51zgAPbgv+AydCrCWgbsRB9T1nl/2lD9bhmtVGafQotQLB4KnUe/8W0TdqC27PtXxuPJ0M+njcoJM2SOeJy8l5XwKfKaVy04cUcXD28Gjl3GEH3th7UNdWfEkKbvslM0lzSI/BRhpOJYKcH6canI5OJE13t8bQqt8HnFieGnPFg13ItB/4hg0lvDi85GxnzC4GPzrvKTRjGxPTH6+KtAEvKVzcyckzSjNF2X+nI/JN9jkCgs8HZaCGttscwEFalrltvbwlxX+17tEl0sjagdp7ssgCF7HrfN7sBSz/EE4kTGHEZXmIHWt7LTJZLv7cE8HaWsS6jlOq3rEDV4Dy4RddmHQYKj1uNczGWZsxjxJLwj804xDKiEJLcRnHPzGpWiBAE16KExQ9sH05s3nuvGY9OcdwGgPQy5ZltSwJG2GqsanezH3Nn6g6AyVwNKMYUvc2MOfeteocvlr8Wwmqry/nRh/59GCBSrXQM1CYXlkAJSaYJvn/Ps53bWYyOyb5i21ZkVGYMkjAn8rO6k+62RjjQP6D6NT7r/YOIY06YmzQXaAQ9ZW35CXW4dn5qHTmcwVb/P8Bk/FDExPfOELC710KdlqbPQHEDp666T+lBwQ+8bAE/LZ9aKUGne9gkJzpp2p107puzTFpLWVOE=
  file: doofinder-magento2.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.*)?$
    repo: doofinder/doofinder-magento2
