<?php
/**
 * @see \Doofinder\Feed\Block\Adminhtml\System\Config\GenerateButton
 */

?>

<div class="actions actions-generate-feed">
    <button class="action-generate-feed" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<script type="text/x-magento-init">
{
    "#doofinder_config_data_feed_cron_settings": {
        "Doofinder_Feed/js/rescheduleFeed": {}
    },
    "#doofinder_config_data_feed_cron_settings_generate": {
        "Doofinder_Feed/js/generateFeed": {
            "ajaxUrl":"<?php echo $block->escapeUrl($block->getAjaxUrl()); ?>"
        }
    }
}
</script>
