<?php
// Workaround that adds compatibility for Magento versions < 2.4.0
if (!isset($escaper)) {
    $escaper = method_exists($block, 'escapeHtml') ? $block : \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Escaper::class);
}
?>
<script>
    require([
        'jquery',
        'mage/translate'
    ], function($, _t){
        $('#clean-integration').click(_ => {
            if (confirm(_t("Are you sure? This action will unsynchronize your search engines with your stores."))) {
                new Ajax.Request('<?= $escaper->escapeUrl($block->getAjaxUrl()) ?>', {
                    loaderArea:     true,
                    asynchronous:   true,
                });
            }
        });
    });
</script>

<?= $block->getButtonHtml(); ?>
