<script>
    require([
        'jquery',
        'mage/translate',
        'Magento_Ui/js/modal/confirm',
        'Magento_Ui/js/modal/alert',
    ], function($, _t, confirmation, alert) {
        $('#create_search_engine').click(_ => {
            confirmation({
                title: _t("Create Search Engine"),
                content: _t("Are you sure? This action will create a search engine within your store."),
                actions: {
                    confirm: function() {
                        new Ajax.Request('<?= $escaper->escapeUrl($block->getAjaxUrl()) ?>', {
                            loaderArea: true,
                            asynchronous: true,
                            onSuccess: function(transport) {
                                if (transport?.responseJSON?.success) {
                                    var hashidElementId = '#doofinder_config_config_doofinder_layer_hash_id'
                                    var hashid = transport?.responseJSON?.data?.hashid || ""

                                    $(hashidElementId).val(hashid)

                                    var event = new Event('change');
                                    $(hashidElementId).get()[0].dispatchEvent(event);
                                } else {
                                    alert({
                                        content: _t(transport?.responseJSON?.message || "An unknown error has occurred while creating the search engine" + " Please take a look into the logs for more information.")
                                    })
                                    return;
                                }

                            },
                            onFailure: function(transport) {
                                alert({
                                    content: _t(transport?.resultJson?.message || "An unknown error has occurred while creating the search engine" + " Please take a look into the logs for more information.")
                                })
                            }
                        });
                    }
                }
            });
        });
    });
</script>

<?= $block->getButtonHtml(); ?>
