<?php $escaper = $block->getEscaper(); ?>
<script>
    require([
        'jquery',
        'mage/translate'
    ], function($, _t){
        $('#manual-indexing').click(_ => {
            const message = _t(
                "This action will update directly the products waiting to be updated in Doofinder. " +
                "Do you want to proceed?"
            );
            if (confirm(message)) {
                new Ajax.Request('<?= $escaper->escapeUrl($block->updateOnClick()); ?>', {
                    loaderArea:     true,
                    asynchronous:   true,
                });
            }
        });
    });
</script>

<?=  $block->getButtonHtml(); ?>
