<?php
if (!isset($escaper)) {
    $escaper = method_exists($block, 'escapeHtml') ? $block : \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Escaper::class);
}
?>
<script>
    require([
        'jquery',
        'mage/translate'
    ], function($, _t){
        $('#manual-indexing').click(_ => {
            if (confirm(_t("This action will update directly the products waiting to be updated in Doofinder. Do you want to proceed?"))) {
                new Ajax.Request('<?= $escaper->escapeUrl($block->updateOnClick()); ?>', {
                    loaderArea:     true,
                    asynchronous:   true,
                });
            }
        });
    });
</script>

<?=  $block->getButtonHtml();
?>
