name: Create Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  create-release:
    name: Build & Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create ZIP archive
        id: vars
        run: |
          tag=${GITHUB_REF#refs/*/}
          zip_path="doofinder-magento2-${GITHUB_REF#refs/*/}.zip"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "zip_path=$zip_path" >> $GITHUB_OUTPUT
          git archive --format=zip -o $zip_path $tag:Doofinder/Feed
      - name: Create release & upload asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.vars.outputs.zip_path }}
          name: Doofinder for Magento 2 - ${{ steps.vars.outputs.tag }}
          generate_release_notes: true
